### ISSUE TITLE
更新最新的5.2版本后一直报错

### ISSUE THREAD

**Issue by andygaowei** [LGH1996/TapClick#2]
![f7f94e7dd5e548c9faf7411116dc120](https://github.com/LGH1996/ADGO/assets/49859852/cd654083-a24f-48c9-8e2a-047273234417)
vivo/PD2231/PD2231:13/TP1A.220624.014/compiler08181419:user/release-keys
BuildTime: Thu Sep 21 16:32:16 CST 2023
VersionCode: 52
java.lang.NullPointerException: Attempt to invoke virtual method 'void b.c.a.a.e.f.h(android.view.accessibility.AccessibilityEvent)' on a null object reference
	at com.lgh.advertising.going.myfunction.MyAccessibilityServiceNoGesture.onAccessibilityEvent(MyAccessibilityServiceNoGesture.java:1)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2668)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2993)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at com.lgh.advertising.going.myclass.MyApplication.onCreate(MyApplication.java:7)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7312)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2372)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8519)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)

**Comment by LGH1996** [comment]
已解

**Comment by LGH1996** [comment]
已解
